// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpGNe-kKSpQIjM8qxsDs2ykhddmj3SRUg',
    appId: '1:206698086287:web:b43144ee12c7bd51b915fa',
    messagingSenderId: '206698086287',
    projectId: 'acaosocial-ipbfoz',
    authDomain: 'acaosocial-ipbfoz.firebaseapp.com',
    databaseURL: 'https://acaosocial-ipbfoz-default-rtdb.firebaseio.com',
    storageBucket: 'acaosocial-ipbfoz.appspot.com',
    measurementId: 'G-067WKTNQYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7U_6m-X0P_qpaEd0J_rvo9PTFbwdEUYc',
    appId: '1:206698086287:android:8eb11fc669f9d1f7b915fa',
    messagingSenderId: '206698086287',
    projectId: 'acaosocial-ipbfoz',
    databaseURL: 'https://acaosocial-ipbfoz-default-rtdb.firebaseio.com',
    storageBucket: 'acaosocial-ipbfoz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTCVJbaqiAQKaB7XKA_mRT4v9rxn-9M6Y',
    appId: '1:206698086287:ios:053e0ffe6cc67f71b915fa',
    messagingSenderId: '206698086287',
    projectId: 'acaosocial-ipbfoz',
    databaseURL: 'https://acaosocial-ipbfoz-default-rtdb.firebaseio.com',
    storageBucket: 'acaosocial-ipbfoz.appspot.com',
    androidClientId: '206698086287-q2ohp1m6ugq9ag23vpftif239qvc9itl.apps.googleusercontent.com',
    iosClientId: '206698086287-954o0qg0qghppjq33gfgj0n2nf9i83mm.apps.googleusercontent.com',
    iosBundleId: 'br.org.ipbfoz',
  );
}
